spring:
  application:
    name: pub-module

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
spring:
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/my_database